#!/bin/bash
set -o errexit

HISTORY="$HOME/.drun_history"
test -f "$HISTORY" || touch "$HISTORY"
INPUT=$(dmenu $@ < "$HISTORY")
test -n "$INPUT"

# aliases
case "$INPUT" in
    chrome)
        CMD="chromium --disk-cache-dir=/tmp/cache" ;;
    morrowind)
	CMD="openmw-launcher" ;;
    nnn)
        CMD="alacritty -e nnn" ;;
    *)
        CMD="$INPUT" ;;
esac

# test if CMD exist in $PATH
hash $(echo "$CMD" | cut -f1 -d ' ')

# write input to history
if ! grep -q "$INPUT" "$HISTORY"; then
    echo "$INPUT" >> "$HISTORY"
    sort "$HISTORY" -o "$HISTORY" &
fi

exec $CMD
